### ISSUE TITLE
Update KDE runtime to 6.X

### ISSUE THREAD

**Issue by notfirefox** [flathub/org.kde.kid3#15]
Update the KDE runtime to a newer version, preferably to the latest version which as of now is 6.6.
For comparison, see this pull request for Okular: https://github.com/flathub/org.kde.okular/pull/341

**Comment by ufleisch** [comment]
This would be simple...

```
-    "runtime-version": "5.15-23.08",
+    "runtime-version": "6.6",
```

...theoretically. However, when I build the Kid3 flatpak like this, the resulting application has only the standard actions in its menu, i.e. not a lot of actions. If I go into the "app container" with `flatpak run --command=sh --devel org.kde.kid3` and search in the filesystem, I can see that the file containing the menu actions is there

```
[📦 org.kde.kid3 ~]$ ls -l /app/share/kxmlgui6/kid3/kid3ui.rc
-rw-r--r-- 2 urs urs 2653 Jan  1  1970 /app/share/kxmlgui6/kid3/kid3ui.rc
```
 
however, the search for this file still uses `kxmlgui5` instead of `kxmlgui6`

```
[📦 org.kde.kid3 ~]$ strace -e file 2>&1 kid3 | less
(..)
statx(AT_FDCWD, "/home/urs/.var/app/org.kde.kid3/data/kxmlgui5/kid3/kid3ui.rc", AT_STATX_SYNC_AS_STAT|AT_NO_AUTOMOUNT, STATX_ALL, 0x7fff0661bbd0) = -1 ENOENT (No such file or directory)
statx(AT_FDCWD, "/app/share/kxmlgui5/kid3/kid3ui.rc", AT_STATX_SYNC_AS_STAT|AT_NO_AUTOMOUNT, STATX_ALL, 0x7fff0661bbd0) = -1 ENOENT (No such file or directory)
statx(AT_FDCWD, "/usr/share/kxmlgui5/kid3/kid3ui.rc", AT_STATX_SYNC_AS_STAT|AT_NO_AUTOMOUNT, STATX_ALL, 0x7fff0661bbd0) = -1 ENOENT (No such file or directory)
statx(AT_FDCWD, "/usr/share/runtime/share/kxmlgui5/kid3/kid3ui.rc", AT_STATX_SYNC_AS_STAT|AT_NO_AUTOMOUNT, STATX_ALL, 0x7fff0661bbd0) = -1 ENOENT (No such file or directory)
statx(AT_FDCWD, "/run/host/user-share/kxmlgui5/kid3/kid3ui.rc", AT_STATX_SYNC_AS_STAT|AT_NO_AUTOMOUNT, STATX_ALL, 0x7fff0661bbd0) = -1 ENOENT (No such file or directory)
statx(AT_FDCWD, "/run/host/share/kxmlgui5/kid3/kid3ui.rc", AT_STATX_SYNC_AS_STAT|AT_NO_AUTOMOUNT, STATX_ALL, 0x7fff0661bbd0) = -1 ENOENT (No such file or directory)
kf.xmlgui: cannot find .rc file "kid3ui.rc" for component "kid3"
(..)
```

Is there something wrong in the flatpak runtime? Are there any flatpak apps using kxmlgui6 working correctly? Since Kid3 is working correctly with Plasma 6 on Arch Linux (which I verified) and probably KaOS (which I did not verify), I doubt if there is something which could be done on the Kid3 side.

I found this in the source code of Kid3 (at the end of _src/app/kde/CMakeLists.txt_), something I made 2023-02-26, commit 304df795b "Fix build with KDE Frameworks 6 (kdesrc-build)", which does not look wrong, but might be no longer needed. If this variable is still not defined, this could be the target of a possible patch, but it does not feel right to "simulate" KDE 5 just to make it run with the 6.6 flatpak runtime.

```
if(QT_VERSION_MAJOR EQUAL 6)
  # TODO KF6: If there something defined?
  if(NOT KXMLGUI_INSTALL_DIR)
    set(KXMLGUI_INSTALL_DIR "${WITH_DATAROOTDIR}/kxmlgui6")
  endif()
endif()
install(FILES kid3ui.rc DESTINATION ${KXMLGUI_INSTALL_DIR}/kid3)
```

**Comment by travier** [comment]
Please give https://github.com/flathub/org.kde.kid3/pull/16 a try. I did not have music files at hand to try it but it looks good.

**Comment by notfirefox** [comment]
> Is there something wrong in the flatpak runtime? Are there any flatpak apps using kxmlgui6 working correctly? Since Kid3 is working correctly with Plasma 6 on Arch Linux (which I verified) and probably KaOS (which I did not verify), I doubt if there is something which could be done on the Kid3 side.

I can tell them apart, because the Flatpak applications that use the older runtime have an oddly sized Adwaita cursor
on my machine. This seems to only affect Flatpak applications that use the older KDE runtime.

**Kid3**
![image](https://github.com/flathub/org.kde.kid3/assets/138280734/9355ff62-d9fc-401f-b39b-2b705fd8695e)

**Okular**
![image](https://github.com/flathub/org.kde.kid3/assets/138280734/09fb5ed7-ae59-4178-bd0e-caabddf1c2b8)

Mind you this is on Fedora Kinoite 40_Beta.1.1 and I am not sure if there's something for Kinoite that 
can be done about it, but upgrading the runtime is certainly one way to go about it.
